name: closed-box-tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: closed-box-tests-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  closed-box-tests:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn test:closed-box
